POST https://message.wprm.com.br/auth/sign
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

###

GET https://message.wprm.com.br/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjAsImlhdCI6MTcxNzA4NzI5NH0.6Bn2y37_PX97XHiHJszOtFeUz_0oA1dohNH2gB3Bjgc
